version: 0.0.13.0.{build}
image: Visual Studio 2015

branches:
  only:
    - latestw_all
    - latestw_all_openssl

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1 -DisableNameChecking
      Invoke-AppVeyorBuild

after_build:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1 -DisableNameChecking
      Install-OpenSSH

before_test:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1 -DisableNameChecking
      Setup-OpenSSHTestEnvironment -Quiet

test_script:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1 -DisableNameChecking
      Run-OpenSSHTests

after_test:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1 -DisableNameChecking
      Upload-OpenSSHTestResults
      
on_finish:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1 -DisableNameChecking
      Publish-Artifact
