version: 0.0.19.0.{build}
image: Visual Studio 2015

branches:
  only:
    - latestw_all

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Invoke-AppVeyorBuild

after_build:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Install-OpenSSH

before_test:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Set-OpenSSHTestEnvironment -Confirm:$false

test_script:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Invoke-OpenSSHTests

after_test:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Publish-OpenSSHTestResults
      
on_finish:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppveyorHelper.psm1
      Publish-Artifact